name: app
type: python:3.5
dependencies:
  python:
    gunicorn: "*"
web:
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET dj_blog.wsgi:application"
  locations:
    "/static":
      root: "static"
      expires: 24h
      passthru: false
    "/":
      passthru: true
      expires: 10m
    "/uploads":
      root: "uploads"
      expires: 30d
      passthru: false

relationships:
  database: "db:postgresql"

disk: 512
mounts:
  "uploads": "shared:files/uploads"

hooks:
  build: |
    pip install -r requirements.txt
