name: app
type: python:3.5
dependencies:
  python:
    gunicorn: "*"
web:
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET app:app"


relationships:
  database: "db:postgresql"

disk: 512
mounts:
  "uploads": "shared:files/uploads"

hooks:
  build: |
    pip install -r requirements.txt