# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 20, 33, 36, 879905, tzinfo=utc), verbose_name='Published at'),
        ),
    ]
