# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
