# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 14:41
from __future__ import unicode_literals
from django.apps import apps
from django.contrib.sites.models import Site

from django.db import migrations, models

def create_redirects(apps):
    Post = apps.get_model("blog", "Post")
    Redirect = apps.get_model("redirects", "Redirect")
    for post in Post.objects.all():
        old_path = '/' + "/".join([
            str(post.pub_date.year),
            '{:02}'.format(post.pub_date.month),
            post.slug
        ])
        new_path = "/posts/" + "-".join([str(post.id), post.slug])
        r = Redirect(site=Site.objects.get_current(), old_path=old_path, new_path=new_path)
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160315_1623'),
    ]

    operations = [
        migrations.RunPython(create_redirects(apps=apps))
    ]
