# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models

def set_dates_on_posts(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    for post in Post.objects.all():
        post.updated = post.pub_date
        post.created = post.pub_date
        post.save()

def do_nothing(apps, schema_editor):
    return True

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160504_1050'),
    ]

    operations = [
        migrations.RunPython(set_dates_on_posts, do_nothing)
    ]
