# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160504_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_post', to='blog.Post'),
        ),
    ]
